# Generated by Django 3.2.6 on 2021-09-27 07:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='homework',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='file',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='file',
            name='author_teacher',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='file', to='courses.teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homework',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='video',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='video',
            name='author_teacher',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='video', to='courses.teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
