# Generated by Django 3.2.6 on 2021-09-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210908_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
