# Generated by Django 3.2.6 on 2021-10-06 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={},
        ),
        migrations.AlterModelOptions(
            name='homework',
            options={},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('author_teacher', 'subject', 'lesson')},
        ),
        migrations.AlterUniqueTogether(
            name='homework',
            unique_together={('author_teacher', 'subject', 'lesson')},
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together={('author_teacher', 'subject', 'lesson')},
        ),
    ]
