# Generated by Django 3.2.6 on 2021-09-09 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_rename_rare_student_course_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='fee',
            field=models.CharField(default='Free', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student_course',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_join', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='student_course',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_join', to=settings.AUTH_USER_MODEL),
        ),
    ]
