# Generated by Django 3.2.6 on 2021-09-13 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20210913_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='lession',
            new_name='lesson',
        ),
    ]
