# Generated by Django 3.2.6 on 2021-09-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_rename_lession_file_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_course',
            name='access',
            field=models.BooleanField(default=True),
        ),
    ]
