# Generated by Django 3.2.6 on 2021-09-23 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20210921_2132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student_Lesson',
        ),
    ]
