# Generated by Django 3.2.6 on 2021-09-23 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20210923_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_lesson',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='courses.lesson'),
        ),
    ]
