# Generated by Django 3.2.6 on 2021-09-23 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_student_lesson_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_lesson',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_student', to='courses.lesson'),
        ),
    ]
